### ISSUE TITLE
find/replace bar is overlapped with code text

### ISSUE THREAD

**Issue by oeway** [jupyter/jupyter#104]
In text editor mode, the find/replace bar is overlapped with the code.

![screen shot 2016-02-04 at 16 08 16](https://cloud.githubusercontent.com/assets/478667/12818962/4b9a3c86-cb59-11e5-97f6-230be68bf3fe.png)

**Comment by dsblank** [comment]
I see that too, in 4.0. I haven't tried 4.1 yet.

**Comment by willingc** [comment]
@oeway @dsblank Thanks for the report on 4.0. Let me give it a try on 4.1.

**Comment by willingc** [comment]
@oeway @dsblank I've verified that the issue also occurs on v4.1 as well. I've opened an issue on jupyter/notebook repo so that it gets more direct attention there. https://github.com/jupyter/notebook/issues/1045

I'm going to close this issue. Feel free to add further comments on the new issue. Thanks!
