### ISSUE TITLE
Segmentation fault (core dumped) when starting a python3 kernel [Resolved]

### ISSUE THREAD

**Issue by AliusEquinox** [jupyter/jupyter#108]
I recently cannot use the notebook anymore with a python3 kernel.

My syslog output :

[78941.591573] jupyter-noteboo[4703]: segfault at bddc24180 ip 00007f0bdb576f5b sp 00007ffcbd5d6bf0 error 4 in socket.cpython-34m.so[7f0bdb567000+16000]

The only thing working is opening a python2 kernel with the notebook using the 'ipython2 notebook' command...

**Comment by takluyver** [comment]
Is that the notebook server or the kernel crashing?

@minrk could this be a pyzmq issue?

**Comment by AliusEquinox** [comment]
The notebook server crash when opening a new pytohn3 kernel

**Comment by takluyver** [comment]
That's very strange. The server should not be doing anything different for a Python 2 or 3 kernel besides starting a different subprocess.

How did you install the notebook and the kernels?

**Comment by minrk** [comment]
Certainly looks like a libzmq/pyzmq issue. What OS is this and how are packages such as pyzmq and lib installed? What versions of pyzmq, libzmq, etc.? If one Python and not the other is working, this is my first suspicion:

1. libzmq was installed
2. pyzmq was installed for Python 3
3. libzmq was upgraded

In which case there are two likely explanations for Python 2 working at the same time:

1. pyzmq was installed for Python 2 more recently (since the latest libzmq upgrade)
2. pyzmq bundles libzmq for Python 2 (this could happen if it was installed before libzmq)

If that's the case, then reinstalling pyzmq with the Python where it's not working should fix it.

**Comment by AliusEquinox** [comment]
Thank for your answers,

First, I'm using Kubuntu15.10.
I've installed libzmq3 and libzmq3-dev with apt-get before installing the notebook. I followed the instruction on jupyter.org to install it with 'pip3 install jupyter'

I also tried to reinstall pyzmq with python 'pip3 install pyzqm' but notebook crashed again.

**Comment by AliusEquinox** [comment]
It seems to works again,

I removed everything from my environment with 'pip3 uninstall ipython[all]' command. On your advice I decide to build from sources the last zmq stable release (4.1.4) and reinstall everything with 'pip3 install ipython[all]'

Thank you for your help !

**Comment by Carreau** [comment]
Thanks, closing the issue as resolved !
