### ISSUE TITLE
math equation display wrong

### ISSUE THREAD

**Issue by hitanvil** [jupyter/jupyter#141]
If I type an equation such as x={x}_{i}+j{x}_{q}={x}_{a}{e}^{j\theta}, its display after rending always has one | after the equation.

**Comment by willingc** [comment]
Hi @hitanvil,

This is an issue that has been reported and should be fixed in notebook version 4.2.
Which version of Jupyter notebook are you currently using? ``jupyter notebook --version`` or by looking in the Help -> About menu option in the notebook which will display like this:
![screen shot 2016-04-19 at 3 13 53 pm](https://cloud.githubusercontent.com/assets/2680980/14657252/93d16858-0641-11e6-9189-4077cf71553d.png)

You may wish to try upgrading if you are using a version prior to 4.2.

Please let us know how it goes.

**Comment by hitanvil** [comment]
Thanks a lot. It is 4.0.0.

My notebook is from Anaconda, which latest version for notebook is 4.0.0.
Waiting Anaconda update then.

Regards,
Yang Xuebin

**Comment by takluyver** [comment]
I'm definitely seeing 4.2 in conda - try running 'conda update notebook'

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
