### ISSUE TITLE
Various Gh-Pages website: Enforce Https ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter#173]
Hi all, 

GitHub now [officially support Https](https://github.com/blog/2186-https-for-github-pages)

> ...blah blah blah .. snip... 
> 
> [you can] configure HTTPS enforcement for your site. With HTTPS enforcement enabled, any HTTP requests to your github.io site will be transparently redirected to HTTPS.
> 
> Starting next Wednesday (June 15, 2016, 12pm PDT), HTTPS enforcement will be required for all **new GitHub Pages sites**

We've often lead the way by enabling new features, any objection in continuing this tradition and enforcing https on our current Gh-Pages, mainly:
- ipython.org
- jupyter.org
- any other per-project pages if they exists ?

@fperez , @ellisonbg , @minrk , @takluyver ?

@rgbkrk, @jdfreder, @captainsafia  thoughts on that ? You might want to do it for nteract as well.

Am I missing any repo we have control over where we might want to do that ?

**Comment by minrk** [comment]
Sounds good to me.

**Comment by rgbkrk** [comment]
You're free to use https://jupyter.github.io right now. However, it doesn't actually _change_ anything for us because we're using custom domains. We encrypt from user/client to CloudFlare, it's up to CloudFlare to encrypt in between their CDN and GitHub's (they do "CNAME flattening" for us).

```
user  <--->  CloudFlare  <---> GitHub Pages
```

We can set CloudFlare to redirect to HTTPS always, as https://ipython.org already works. We do the auto-redirect for a few other properties cdn.jupyter.org and nbviewer.jupyter.org already.

**Comment by Carreau** [comment]
> HTTPS is not supported for GitHub Pages using custom domains.

Ah thanks for pointing this out. 

> We can set CloudFlare to redirect to HTTPS always, as https://ipython.org already works

If possible I would be +1 to do that on cloudflare. if possible.

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. Github pages supports https now, and I just enabled it for jupyter.github.io / jupyter.org (see https://github.com/jupyter/jupyter.github.io/issues/752 )

Happy hacking! :bowtie:
