### ISSUE TITLE
Terminal display settings: display width too small

### ISSUE THREAD

**Issue by xtYao** [jupyter/jupyter#197]
Dear Jupyter team,

Another issue with the Terminal session opened in Jupyter: the width of the displayed region is too small. The narrow screen is making it hard to split it and multitasking with some programs (like in emacs).

Is there a way to adjust this?

Thanks,
Xiaotong

**Comment by ivanov** [comment]
Hey there @xtYao , I'm going through old issues and it seems to me that it makes sense to close this one. I think the terminal component has gone through several versions since you made this request and how is not limited to the narrow width you mentioned when you opened this issues.

Thanks  and happy hacking! :bowtie:
