### ISSUE TITLE
python2 kernel can't be found (despite python2 installation)

### ISSUE THREAD

**Issue by rgerkin** [jupyter/jupyter#207]
I am getting this error:  
`jupyter_client.kernelspec.NoSuchKernel: No such kernel named python2`

in my [Travis-CI log](https://travis-ci.org/openworm/ChannelWorm/builds/160294499) (scroll to bottom).  I don't understand it because all previous steps in the build used python2.7, so I would expect Jupyter to find a kernel for python2.

**Comment by takluyver** [comment]
It looks like you install `jupyter_client` but not `ipykernel`. `jupyter_client` does not depend on `ipykernel`, because you can use it to talk to other kernels.

The higher level packages like `notebook` do express a dependency on `ipykernel`, so that the applications will work 'out of the box' with no extra pieces. But that isn't the case if you just install `jupyter_client`.

**Comment by rgerkin** [comment]
@takluyver Thanks! What subset of jupyter do I need to install to just execute notebooks via the API?  Or should I just not bother and require the whole jupyter install?

**Comment by takluyver** [comment]
The simplest API for executing notebooks is nbconvert's [execute preprocessor](https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py). For that, you'd want `nbconvert` and `ipykernel` installed (assuming you're executing Python notebooks).

**Comment by rgerkin** [comment]
Thanks, that worked!
