### ISSUE TITLE
Jupyter Desktop App

### ISSUE THREAD

**Issue by kennysong** [jupyter/jupyter#30]
Since it looks like Jupyter/iPython has stabilized, perhaps [this project](https://github.com/mangecoeur/ipython-desktop) or a variant can be (re)started. I think it would be quite useful and a huge step for user-friendliness to not have to interact with the CLI + a browser for the notebooks. Making it cross-platform seems doable using node-webkit or electron (is there a good Python alternative?).

With Jupyter, it also seems possible to decouple the desktop app from a specific kernel, so the same desktop app could be used for all the supported languages (?). 

It probably makes sense to pool our efforts if others are interested in this. 

@mangecoeur what do you think?

**Comment by mangecoeur** [comment]
I think the ![atom integration](https://github.com/jupyter/atom-notebook) is the most promising avenue (and is already under the jupyter project apparently). Since atom already provides advanced text editing features and is readily hackable I really like the idea of using it for desktop iPython. There's loads of work to do still, as will as plenty of basic design decisions - starting with whether it should just be an atom plugin or an app forked from atom. I don't think there are any good python alternatives to NW/electron - happy to be shown wrong though, the world could definitely use an ipython notebook renderer written in python.

**Comment by rgbkrk** [comment]
I'm certainly a fan of this.

My personal opinion is that we need our JavaScript broken out into smaller reusable packages, which has already been done for the [output area](https://github.com/jupyter/jupyter-js-output-area) and the primary [services](https://github.com/jupyter/jupyter-js-services) of the notebook - session, kernel, contents. Note that the contents API is not necessary for a pure desktop application.

The output area is already being used in [sidecar](https://github.com/nteract/jupyter-sidecar) which *is* an Electron app. Additionally, there's [Hydrogen](https://github.com/willwhitney/hydrogen) and the [Atom Notebook](https://github.com/jupyter/atom-notebook) - both Atom packages.

## Issues

The most common issue we (developers of the above mentioned projects) have faced is native extensions, especially node-zmq. In particular, each release of V8 ends up having inconsistencies which are addressed in [nan](https://github.com/nodejs/nan) (Native abstractions for Node.js). On top of that, actually building it on the various platforms (as in, on people's machines) is not the best story for Windows (requires specific version of Visual Studio). We really need to be shipping around the built binaries for zmq across Windows, OS X, and Linux in order to take advantage of the auto-updating.

You may ask (as does ipython-desktop above) "why not just use the notebook server itself to reach kernels"? My primary reasons for wanting to steer clear of this are all about security, primarily with respect to cross origin issues across websockets and shielding from other issues likely to come up with running a local server on machines (where not everyone understands they're running a server). I would be amenable to a very opinionated, very locked down, glorified zmq-websocket bridge.

**Comment by kennysong** [comment]
The atom-notebook integration looks great – I might start using that in the meantime. However, I don't know if it's a good general solution for a desktop app. It seems equally problematic to tell people to install and access Jupyter through Atom as through a browser. Restricting a fork of Atom to solely wrap Jupyter seems slightly better, but could be very bloated and potentially slow. Just my opinion though.

Something standalone and one click away in your task bar seems like the nicest solution (like how Mathematica or Matlab would be used).

@rgbkrk I'm not totally sure what you mean by not using the notebook server to reach kernels. Instead of having nw start the Jupyter server and just pointing the nw browser to localhost, we should have a custom webpage on the client that uses the [JS APIs](http://jupyter.org/jupyter-js-services/) to interact with Jupyter functionality?

**Comment by willingc** [comment]
@rgbkrk I think it's reasonable to close this issue at this time. Agree?

**Comment by rgbkrk** [comment]
Yeah, https://github.com/nteract/nteract is the realization of the above vision with Electron.
