### ISSUE TITLE
Unable to install Jupyter  in Ubuntu 14.04

### ISSUE THREAD

**Issue by rakashi** [jupyter/jupyter#346]
I am trying to install jupyter using 

sudo -H pip install jupyter

python version as 2.7.6 also I ma having python 3.4.3

But its giving the following error

Can anyone help me how to resolve this issue
![screenshot from 2018-05-23 13 44 07](https://user-images.githubusercontent.com/30826794/40412216-4ad18daa-5e90-11e8-9a65-94b16856c435.png)

**Comment by takluyver** [comment]
Try installing it using Python 3: `python3 -m pip install jupyter` (Probably `pip3 install` also works,  but the `python3 -m ` way lets you nicely control which Python you're installing on.

It's also not advised to use `sudo` with pip, because it can mess up your system. Using the `--user` flag for pip is safer - it will install into your home directory. Or you can use virtualenvs or conda to create an isolate environment.

**Comment by b1weber** [comment]
Hi,
Have you updated your system?
sudo apt update
then
sudo apt upgrade

Also, I used to install everything individually until I started using Anaconda.  You might want to look at it.  It bundles everything nicely.
It can also be installed through your Ubuntu Software tool.
Keep at it.,
Bob
________________________________

**Comment by IIAOPSW** [comment]
I am also having this issue. 

In my case the error is "404 Client Error: Not Found for url: https://pypi.org/simple/jupyer/" 

And no I cannot just use the --user option because I am installing this on a machine with multiple users and I want all of them to have it. sudo -H is the appropriate solution afaik. Weirdly I do not get any error when I exclude the sudo -H

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
