### ISSUE TITLE
Unable to load jspdf dependency in jupyter notebook

### ISSUE THREAD

**Issue by Prakriti-nith** [jupyter/jupyter#352]
I tried to load the dependency `http://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js` in jupyter notebook. However, it is not working and produces `jsPDF is not defined` error when I used it further.
I think this dependency might be conflicting with the existing code of jupyter notebook. Is there any way to make this work?

**Comment by drorhilman** [comment]
I have similar problem with other js imports I try (echarts). 
The general problem is that code injected with js is not executed (and thus, the global name such as 'jspdf') is not injected.  
NOT sure how to solve this

**Comment by choldgraf** [comment]
Hello there 👋

It looks like this issue might be well-scoped for discussion on the [Jupyter Community Discourse](https://discourse.jupyter.org) instead of on a GitHub repository. We're using Discourse for more **general Q&A and discussion**, and will keep the GitHub repositories focused around repository-specific and actionable items. If you're willing, I recommend opening up a thread there if you've still got questions! Hopefully it'll be easier to find answers and input there ✨✨

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
