### ISSUE TITLE
jupyter loads python kernel instead of r kernel for conda env

### ISSUE THREAD

**Issue by rbavery** [jupyter/jupyter#397]
Hello all, I'm trying to create a conda environment, associate it with my user account on a jupyterhub instance, and have that conda environment's default kernel be R. Here's what I've tried

```
conda create -n r-environment r-essentials r-base r-irkernel
source activate r-environment
ipython kernel install --user --name r-environment
```
But then when I go to New > r-environment, Jupyter uses a python kernel.

It looks like the ir-kernel is not installed in the right location when I called ipython kernel install

```
(r-environment) bash-4.4$ jupyter kernelspec list
Available kernels:
  geo              /home/rave/.local/share/jupyter/kernels/geo
  ir               /home/rave/.local/share/jupyter/kernels/ir
  r-environment    /home/rave/.local/share/jupyter/kernels/r-environment
  python3          /usr/local/share/jupyter/kernels/python3
```

And when I try to start a notebook with that `ir-kernel` the notebook dies (I think `ir-kernel` is associated with R in the pic below)

![selection_539](https://user-images.githubusercontent.com/22258697/53044324-862a1680-343f-11e9-9e6d-d1966e2016d8.png)

![selection_538](https://user-images.githubusercontent.com/22258697/53044353-993ce680-343f-11e9-8e8c-700fbcd7762d.png)

Any help is greatly appreciated and thank you in advance!

**Comment by rbavery** [comment]
Also, I tried the following to install the kernelspec from within R, following instructions from 
https://github.com/IRkernel/IRkernel
```
source activate r-essentials
R
```
then in the R terminal
```
install.packages('IRkernel')
IRkernel::installspec()  # to register the kernel in the current R installation
```
But this doesn't set the kernel in the conda environment and for some reason I have a python3 kernel in my r-essentials environment (I changed the name to r-essentials after trying a fresh install)

```
(r-essentials) bash-4.4$ jupyter kernelspec list
Available kernels:
  geo        /home/rave/.local/share/jupyter/kernels/geo
  ir         /home/rave/.local/share/jupyter/kernels/ir
  python3    /home/rave/miniconda3/envs/r-essentials/share/jupyter/kernels/python3
```

Furthermore, I still see R as an option in the Jupyter button to start a new notebook. but the kernel still dies as above.

**Comment by rbavery** [comment]
**update**
After removing kernelspecs for python and r, which were in swapped locations (I want the r kernel to be in my r environment and python in base environment), I somehow wound up with the kernels in their correct locations just by removing the misplaced kernels

```
(r-essentials) bash-4.4$ jupyter kernelspec list
Available kernels:
  geo        /home/rave/.local/share/jupyter/kernels/geo
  ir         /home/rave/.local/share/jupyter/kernels/ir
  python3    /home/rave/miniconda3/envs/r-essentials/share/jupyter/kernels/python3
(r-essentials) bash-4.4$ jupyter kernelspec remove ir
Kernel specs to remove:
  ir                    /home/rave/.local/share/jupyter/kernels/ir
Remove 1 kernel specs [y/N]: y
[RemoveKernelSpec] Removed /home/rave/.local/share/jupyter/kernels/ir
(r-essentials) bash-4.4$ jupyter kernelspec remove python3
Kernel specs to remove:
  python3               /home/rave/miniconda3/envs/r-essentials/share/jupyter/kernels/python3
Remove 1 kernel specs [y/N]: y
[RemoveKernelSpec] Removed /home/rave/miniconda3/envs/r-essentials/share/jupyter/kernels/python3
(r-essentials) bash-4.4$ jupyter kernelspec list
Available kernels:
  geo        /home/rave/.local/share/jupyter/kernels/geo
  ir         /home/rave/miniconda3/envs/r-essentials/share/jupyter/kernels/ir
  python3    /usr/local/share/jupyter/kernels/python3
```

I then couldn't see any option to start an R notebook, so then I tried associating the r conda environment with jupyter again, using the python -m option (unlike the first time). This seems to produce a different but still undesirable result

`python -m ipykernel install --user --name r-essentials`

I now have a kernel viewble in Jupyterhub that says `r-essentials` rather than just R (when the R kernel was not in my R environment, see above). However, the notebook is still a python notebook
![selection_541](https://user-images.githubusercontent.com/22258697/53065354-23a53a80-3480-11e9-9ed3-fa2e18ab2648.png)

**Comment by lbenyakar** [comment]
Hello @rbavery,

It's been quite a long time since this issue is open, but I have encounter the same problems and find a solution who work in my case...

I have created a conda environnement exactly like you did but without the r-essentials, and i add jupyter notebook.
When i checked my kernels, I have this : 

`(r_env) > jupyter kernelspec list
Available kernels:
  python3    C:\Users\lb\AppData\Local\miniconda3\envs\r_env\share\jupyter\kernels\python3
  ir         C:\Users\lb\AppData\Roaming\jupyter\kernels\ir`

So I did this : 

`(r_env) > jupyter kernelspec uninstall ir
Kernel specs to remove:
  ir                    C:\Users\lb\AppData\Roaming\jupyter\kernels\ir
Remove 1 kernel specs [y/N]: y
Removed C:\Users\lb\AppData\Roaming\jupyter\kernels\ir

(r_env) > jupyter kernelspec list
Available kernels:
  python3    C:\Users\lb\AppData\Local\miniconda3\envs\r_env\share\jupyter\kernels\python3`

(By removing the kernels, they don't appear in the right path like you :( )

And lastly, I install my IRkernel with this command : 

`(r_env) > conda install -c conda-forge r-irkernel `

I get : 

`(r_env) > jupyter kernelspec list
Available kernels:
  ir         C:\Users\lea2\AppData\Local\miniconda3\envs\r_env\share\jupyter\kernels\ir
  python3    C:\Users\lea2\AppData\Local\miniconda3\envs\r_env\share\jupyter\kernels\python3`

And It works perfectly for me !

(I have saw your issue on the IRkernel github too  
[#615](https://github.com/IRkernel/IRkernel/issues/615), so I may have do a little mix from what you did )

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one, as it sounds like there's a workaround.

Thanks everyone and happy hacking! :bowtie:
