### ISSUE TITLE
Signature Preview breaks definition into many lines

### ISSUE THREAD

**Issue by sshleifer** [jupyter/jupyter#419]
The shift-tab auto-completion display for **some** functions breaks their signature into entries of one argument per line that make them much harder to read. It is the same if you type `svm.train?` and open up the larger docstring viewer.

As far as I can tell this doesn't happen for library code like `np.array`, or functions declared inside the notebook. Only files I'm editing in pycharm. It might somehow be relatted to `%load_ext autoreload` but I'm not sure. Does anybody know how to fix?

[](url)
<img width="721" alt="jupyter_multiline" src="https://user-images.githubusercontent.com/6045025/56105534-9adfd380-5ef1-11e9-846e-50fede7f98c9.png">

```
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
notebook==5.7.8
ipython==7.4.0
```

**Comment by choldgraf** [comment]
Hello there 👋

It looks like this issue might be well-scoped for discussion on the [Jupyter Community Discourse](https://discourse.jupyter.org) instead of on a GitHub repository. We're using Discourse for more **general Q&A and discussion**, and will keep the GitHub repositories focused around repository-specific and actionable items. If you're willing, I recommend opening up a thread there if you've still got questions! Hopefully it'll be easier to find answers and input there ✨✨

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
