### ISSUE TITLE
Button to switch from Notebook to Jupyterlab and back

### ISSUE THREAD

**Issue by digital951** [jupyter/jupyter#420]
This is more of a feature request. We would like to see a button to switch to Jupyterlab and back to the notebook. We run Jupyterhub and there is a need for users to switch back and forth between them. They currently have to edit the URL to make this happen.

**Comment by choldgraf** [comment]
Hello there 👋

It looks like this issue might be well-scoped for discussion on the [Jupyter Community Discourse](https://discourse.jupyter.org) instead of on a GitHub repository. We're using Discourse for more **general Q&A and discussion**, and will keep the GitHub repositories focused around repository-specific and actionable items. If you're willing, I recommend opening up a thread there if you've still got questions! Hopefully it'll be easier to find answers and input there ✨✨

**Comment by rraadd88** [comment]
Just need to switch between `/lab?` and `/tree?`
e.g. `https://localhost:8888/lab?` and `https://localhost:8888/tree?`.

**Comment by lahwaacz** [comment]
Jupyter Notebook 7 has a _View > Open JupyterLab_ button in the context menu, but JupyterLab 4 does not have an equivalent button to open the Notebook interface.

**Comment by jtpio** [comment]
It has one but it's under the `Help` menu:

![image](https://github.com/jupyter/jupyter/assets/591645/5ecb5634-4ed9-4829-8738-2512b7a80966)

Maybe it should be moved to the `View` menu?

There is also a dropdown in the Notebook toolbar to switch between interfaces:

![image](https://github.com/jupyter/jupyter/assets/591645/31f1e110-081d-4537-bec3-0902b4710483)

**Comment by lahwaacz** [comment]
+1 for moving _Launch Jupyter Notebook File Browser_ from _Help_ to _View_.

**Comment by jtpio** [comment]
@lahwaacz would you like to open an issue on the Notebook repo to suggest this? https://github.com/jupyter/notebook

Thanks!

**Comment by lahwaacz** [comment]
It's for JupyterLab so https://github.com/jupyterlab/jupyterlab/ should be better, right?

**Comment by jtpio** [comment]
Normally yes. But in the case of Notebook 7 these menu entries are provided via a JupyterLab extension, which lives in https://github.com/jupyter/notebook/tree/main/packages/lab-extension.

**Comment by ivanov** [comment]
awesome, closing this here, thanks everyone!
