### ISSUE TITLE
Kernel didn't start correctly

### ISSUE THREAD

**Issue by mahdisarikhani** [jupyter/jupyter#423]
I opened a notebook file on a Linux system in a directory that contains a random.py file, jupyter kernel didn't start and show an error about random.py file. I have this problem only on Linux.

**Comment by choldgraf** [comment]
Hello there 👋

It looks like this issue might be well-scoped for discussion on the [Jupyter Community Discourse](https://discourse.jupyter.org) instead of on a GitHub repository. We're using Discourse for more **general Q&A and discussion**, and will keep the GitHub repositories focused around repository-specific and actionable items. If you're willing, I recommend opening up a thread there if you've still got questions! Hopefully it'll be easier to find answers and input there
