### ISSUE TITLE
Ambiguous instructions for installing python2 and python3 kernels, Big Split path issues?

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/jupyter#52]
In attempting to collaborate with @suchow, we ran into an issue with his jupyter notebook having been installed through python2 and my having written the notebook with a python3 kernel in mind.

He had an ipython3 version of the notebook with `python3` as its kernel, but that would not run `Python 3.5`. 

In trying to figure out how to fix the original problem (i.e., a jupyter notebook installed through `python2` not having access to a `python3` kernel) I began a long trek through a lot of conflicting documentation, this issue is the trail as I tried to recreate it (I am guessing I left out some parts). 

I ended up at this documentation which only says that a Python kernel is installed when you installed the notebook https://github.com/jupyter/jupyter/blob/master/docs/source/install.rst. 

Look at http://jupyter.cs.brynmawr.edu/hub/dblank/public/Jupyter%20Help.ipynb#1.4.2-Enable-Python-3-kernel but that seems to use the `~/.ipython/kernels/` path rather than the post Big Split path which seems to be `~/Library/Jupyter` or `/usr/local/share/jupyter` (since `~/.jupyter` is for config files, not data files and kernels are data files). 

Eventually I found http://jupyter.readthedocs.org/en/latest/migrating.html#kernels, which says

> You can see where the file is with `jupyter kernelspec list`, and then modify `kernels/python3/kernel.json` by hand. [a2km](https://github.com/minrk/a2km) is an experimental project that tries to make these things easier.

But the file path is not returned when I run `jupyter kernelspec list`, all it does is return
```
Available kernels:
  python3
```

And going from to https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages includes no instructions for how to install a `Python 2` kernel if you began with a `Python 3` kernel (or vice-versa). 

I only noticed now that 

> `IPython.kernel` → `jupyter_client`, `ipykernel` (`IPython.kernel` became two packages - one for the client-side APIs, one for the IPython kernel for Jupyter)

which leads me to look at http://ipython.org/ipython-doc/dev/development/kernels.html

Which suggests (contrary to the above jupyter migration documentation)

> To see the available kernel specs, run:
>
>        ipython kernelspec list

(which also only returns a list of the kernels with no path)

And also says: 
<table border="1" class="docutils">
<colgroup>
<col width="10%"/>
<col width="47%"/>
<col width="43%"/>
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">&nbsp;</th>
<th class="head">Unix</th>
<th class="head">Windows</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td>System</td>
<td><p class="first"><tt class="docutils literal"><span class="pre">/usr/share/jupyter/kernels</span></tt></p>
<p class="last"><tt class="docutils literal"><span class="pre">/usr/local/share/jupyter/kernels</span></tt></p>
</td>
<td><tt class="docutils literal"><span class="pre">%PROGRAMDATA%\jupyter\kernels</span></tt></td>
</tr>
<tr class="row-odd"><td>User</td>
<td colspan="2"><tt class="docutils literal"><span class="pre">~/.ipython/kernels</span></tt></td>
</tr>
</tbody>
</table>

which conflicts with the above claim that it should be in either `/usr/local/share/jupyter/kernels` or  `~/Library/Jupyter` (if local) on OSX Unix systems, and suggests continued use of the `~/.ipython/kernels` path (which I should mention, does not exist on my machine). 

I'm genuinely baffled as to how to either instruct someone else to install a `python3` kernel on their machine or to install a `python2` kernel on mine…

Just to check these are the errors I got when I tried to run 
```
jupyter kernelspec install python2
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 8, in <module>
    main()
  File "/usr/local/bin/jupyter-kernelspec", line 5, in main
    KernelSpecApp.launch_instance()
  File "/usr/local/lib/python3.4/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/usr/local/lib/python3.4/site-packages/jupyter_client/kernelspecapp.py", line 177, in start
    return self.subapp.start()
  File "/usr/local/lib/python3.4/site-packages/jupyter_client/kernelspecapp.py", line 113, in start
    replace=self.replace,
  File "/usr/local/lib/python3.4/site-packages/jupyter_client/kernelspec.py", line 208, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/shutil.py", line 296, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'python2'
```
Which returned similar errors when run with `python2.7`,`python27`,`PYTHON2`,`PYTHON2.7`,`PYTHON27` and even `python`. 

Regardless, the amount of hoops I had to go through and the number of conflicts I ran into suggested to me that this needs more documentation on how to do. 

I'm happy to help write the necessary changes in all the places I found (plus a number of stackexchange answers that I think may be inconsistent with the Big Split… I've posted links to at the bottom of this Issue), I just need to know how to solve the problem at least on my system before I can help with fixing the inconsistent documentation. 

No matter what, it would seem to make sense to point out that there are two potential python kernels that the jupyter notebook can use, and I would argue that installation instructions for running both side-by-side should be included in the core documentation (or at least in the [list of available kernels page] (https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages)). 

relevant Stack-overflow answers with ambiguous relevance due to big split:

http://stackoverflow.com/questions/30492623/using-both-python-2-x-and-python-3-x-in-ipython-notebook
especially the answer: http://stackoverflow.com/a/30493155/1816995
http://stackoverflow.com/questions/32258277/how-can-i-run-python-2-7-3-4-notebooks-side-by-side-in-jupyter-ipython
http://stackoverflow.com/questions/29773954/change-ipython-3-for-python-3-kernel-to-python2-for-the-cluster-too
http://stackoverflow.com/questions/28831854/how-do-i-add-python3-kernel-to-jupyter-ipython

**Comment by willingc** [comment]
@michaelpacer and @suchow I'm sorry you ran into this frustration. Thank you for sharing detailed notes and for your offer to assist with improving docs and the upgrade experience for others.

Pinging @minrk @Carreau on this. It looks like Homebrew was used to install Python 3 at some point. When pip installing Jupyter or upgrading from ipython to Jupyter when a brewed Python is also installed, it looks like there is path confusion.

**Comment by Carreau** [comment]
Getting back from conference will try to catch-up on that,

**Comment by Carreau** [comment]
> But the file path is not returned when I run jupyter kernelspec list, all it does is return
> 
> Available kernels:
>   python3

That should be fix on master: 

```
$ jupyter kernelspec list
Available kernels:
  haskell      /Users/bussonniermatthias/Library/Jupyter/kernels/haskell
  julia-0.3    /Users/bussonniermatthias/Library/Jupyter/kernels/julia-0.3
  julia-0.4    /Users/bussonniermatthias/Library/Jupyter/kernels/julia-0.4
  julia-0.5    /Users/bussonniermatthias/Library/Jupyter/kernels/julia-0.5
  python2      /usr/local/share/jupyter/kernels/python2
  python3      /usr/local/share/jupyter/kernels/python3
```

(maybe we should compress user here to have `~` instead of full path thought ?) 


The installatin instruction for kernels can partially be found here: http://ipython.readthedocs.org/en/latest/install/kernel_install.html but is a bit out of date.

One of the reason it is a bit complicated with the python kernels is for historical reason they were bundle with the notebook before, and it is common to install many kernels from different environment. 

A few things: 

Installing a kernelspec will install the kernel for the interpreter you use to install the kernelspec. 
There are several equivalent way to install kernelspec. 

Historically : `ipython kernelspec install-self` this one might not be needed as it will just create on disk the in-memory version which is exposed when you launch the notebook. Because the only guarantied kernel that was available with the notebook was the IPython one started with the same python interpreter as the notebook. 

Now it is not a self-install as the kernel is a separate package called `ipykernel`. You can still install with `ipython kernel install [--name NAME]`, but it will again use the same interpreter as the IPython one. So if you have `ipython2` and `ipython3` availlable you can do both `ipython2 kernel install --name python2` and `ipython3 kernel install --name python3` (the name should be picked correctly if you are not explicit but this is an example). 

If you have a venv you can `source activate MyEnv` and then do as above, with `--name MyEnv`.

And if you are adventurous or know what you are doing, you can `path/to/python -m ipykernel install [--help | --name NAME | --display-name NAME]`. 

I'll try to make some updates, hope it make sens.

**Comment by michaelpacer** [comment]
So when I tried your adventurous solution, it suggested `ipykernel` did not exist…

```
/usr/bin/python2.7 -m ipykernel install --name python2
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named ipykernel
```

and if i install in a virtualenv, will that make that version of the notebook only available within that virtualenv?

Can you use `ipython3` to install the `python2` kernel or vice versa?

**Comment by michaelpacer** [comment]
Verified, you can use `ipython3` to install the `python2` kernel:

$ ipython3 kernel install --name python2
Installed kernelspec python2 in /usr/local/share/jupyter/kernels/python2

Excellent.

**Comment by Carreau** [comment]
> $/usr/bin/python2.7 -m ipykernel install --name python2
> /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named ipykernel

So that the weird system python that have no pip. Seen in person. 

> Can you use ipython3 to install the python2 kernel or vice versa?

No, by using --name you just rename the kernel. 
The sever might need a restart after kernel update.

**Comment by michaelpacer** [comment]
Ok, so @Carreau thanks for the help on this. 

Just to update this for others, if you have a `virtualenv` that uses either `python2` or `python3` (e.g., `mkvirtualenv py2 -p "$(which python2)"`or  `mkvirtualenv py3 -p "$(which python3)"`), then you can go into that `virtualenv`, use `pip install ipykernel` and then `ipython kernel install` and it will write the correct path to the `virutalenv` linked `python` to the jupyter kernel list (`python2` or `python3` will be included if you run `jupyter kernelspec list`).

Is that right @Carreau?

**Comment by Carreau** [comment]
Yep

**Comment by michaelpacer** [comment]
Where would be the place that a canonical walk through that explains this process could go? Happy to contribute it (the raw materials are on this issue page), but I don't know which place would make the most sense.

**Comment by Carreau** [comment]
see https://github.com/ipython/ipython/pull/8890 and https://github.com/ipython/ipython/pull/8877 I guess.

**Comment by maxeywen** [comment]
I have read this whole thread and most all of the links MIchael shared here.  I agree with him that it simply is not clear.  I installed Jupyter notebook through Python 2 and now I can not accept any Python 3 files without using a VM to do that work.  I am on Fedora 23 and I do not see the need for using Anaconda outside the chance it makes this simpler.  Has anyone here found updated documentation that actually works?  

I last tried this on a new F23 install and while I can allegedly open a new notebook with the Py3 kernel, it dies within seconds.

http://jupyter.cs.brynmawr.edu/hub/dblank/public/Jupyter%20Help.ipynb#1.4.2-Enable-Python-3-kernel

**Comment by willingc** [comment]
@maxeywen I'm glad you found a description on Stack Overflow and the notebook is now running for you.

In the future, you may find these two gists with bash scripts helpful in troubleshooting:
[checkmypython.sh](https://gist.github.com/willingc/9ff70a642b54023cc8d4)
[checkmypackages.sh](https://gist.github.com/willingc/9dd6efb251399e84468f)

**Comment by maxeywen** [comment]
Thanks for those.  I went back and reviewed this installation page https://jupyter.readthedocs.org/en/latest/install.html (which neither Michael or I had linked to yet) and I think this page should be more clear about needing to run both 'pip install jupyter' and 'pip3 install jupyter'.   (if that's indeed correct)

**Comment by takluyver** [comment]
To enable a Python 3 kernel when you're running the server on Python 2, it should be sufficient to do:

```
pip3 install ipykernel
python3 -m ipykernel.kernelspec --user
```

And if you run the server on Python 3 and want to add a Python2 kernel, do exactly the same on Python 2:

```
pip2 install ipykernel
python2 -m ipykernel.kernelspec --user
```

**Comment by Carreau** [comment]
@takluyver can you add that to IPykernel documentation page ?
Installing multiple**IPykernel** seem to belong there and not in Jupyter.

**Comment by minrk** [comment]
closed by ipython/ipython#9103

**Comment by BiondiVini** [comment]
To rename the notebook kernel you must configure the kernel in the folder (the kernel.json file)
You'll have something like this
{
 "language": "python",
 "display_name": "Python 3", <---change the name
 "argv": [
  "/usr/bin/python3",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ]
}

**Comment by blender** [comment]
The instructions on how to install multiple python kernels should really be written in bold on the front page

**Comment by Carreau** [comment]
> The instructions on how to install multiple python kernels should really be written in bold on the front page

The IPython kernel is "just another kernel", there is not much reason to make it much more visible than say, Julia, R, Haskell.

**Comment by takluyver** [comment]
Well, it's not quite "just another kernel", being the kernel that comes with Jupyter, and probably the most well known. But different things are important to different people, and the home page is only so big. ;-)

Instructions on installing multiple Python kernels have just been cleaned up a bit more:
http://ipython.readthedocs.org/en/latest/install/kernel_install.html

We could probably still make that easier to discover.

**Comment by maxeywen** [comment]
After following this and struggling with it myself I have come to 2 conclusions

(1) setting up Jupyter for Python 2.x and Python 3.x is not a straightforward process.  there are too many permutations of scenarios that lead a user to the point of installing their 2nd python kernel, whichever it is.  what's the os? default python version? using anaconda?  if not anaconda, using virtenv?  what order did you install everything in?  is this a fresh install of jupyter or an upgrade from ipython?  yada yada ... this is quite a lot for the jupyter team to document.  i do thank them for trying to accommodate everyone's needs.  thank you all!
(2) it seems to me as a user that this is more of a Python issue than a Jupyter issue because these problems disappear once the Python community moves solely to Python 3.  so here is hoping we do that sooner than later*

* says the guy required to spend 95% of his time in Python 2.x right now

**Comment by takluyver** [comment]
At some point in the future, we will probably make the notebook server require Python 3 (but still be able to run Python 2 code in notebooks). This will simplify the explanation a bit, because it will just be 'setting up a Python 2 kernel', rather than 'setting up a Python 2 or 3 kernel, whichever one you're not running the notebook with'.

**Comment by kirk86** [comment]
@takluyver Thank you the information on how to add additional python kernels.
I just have a question because I would like to clarify some things regarding the additional python kernels.

I am on linux (arch) and I had as default python3.  I also had installed python2.
I installed each version equivalently via pip2 and pip3.

When I issue the command `jupyter-kernelspec list`, I see the following output.
`Available kernels:
            python3: /usr/lib/python3.5/site-packages/ipykernel/resources`

Equivalently when I issue the command `ipython2 kernelspec list` or `ipython kernelspec list`, I see
the following output.

`Available kernels:
             python2: /usr/lib/python2.7/site-packages/ipykernel/resources`

After I used your commnad as you indicated `python2 -m ipykernel.kernelspec --user`, now when I issue `jupyter-kernelspec list`, I see the following:

`Available kernels:
            python3: /usr/lib/python3.5/site-packages/ipykernel/resources
            python2: /home/username/.local/share/jupyter/kernels/python2`.

My questions are the following if I delete the folder `/home/username/.local/share/jupyter/kernels` will that restore the output of `juypter-kernelspec list` to its previous state.

If instead of: 

`Available kernels:
            python3: /usr/lib/python3.5/site-packages/ipykernel/resources
            python2: /home/username/.local/share/jupyter/kernels/python2`.

I would, like to have something like this:

`Available kernels:
            python3: /usr/lib/python3.5/site-packages/ipykernel/resources
            python2: /usr/lib/python2.7/site-packages/ipykernel/resources`.

How do I do that?

If I use the command `python2 -m ipykernel.kernelspec` without the `--user` option will that work.

For instance when I tried to issue the command:

`sudo jupyter-kernelspec install '/usr/lib/python2.7/site-packages/ipykernel/resources`

I got the following response:

`Installed kernelspec resources in /usr/local/share/jupyter/kernels/resources`

But when I checked the `jupyter-kernelspec list`, it didn't change anything and it gave me the same output as before:

`Available kernels:
             python3    /usr/lib/python3.5/site-packages/ipykernel/resources
             python2    /home/username/.local/share/jupyter/kernels/python2
`

Instead of the desired:

`Available kernels:
          python3    /usr/lib/python3.5/site-packages/ipykernel/resources
          python2    /usr/lib/python2.7/site-packages/ipykernel/resources
`

**Comment by takluyver** [comment]
You did do a systemwide installation by leaving off the `--user` parameter, but the user-level kernel spec with the same name (i.e. `~/.local/share/jupyter/kernels/python2`) takes priority over the systemwide one. If you remove the user-level one, you should see the system level one as you expect.

The kernel resource directory being inside the `ipykernel` installation is a special case for the 'native' kernel - the one that runs on the same Python executable as the server. We do this so that the notebook works out of the box, without requiring any extra setup. If you want them to be homogeneous, install a `python3` kernel in the same way that you did for `python2`. That will take priority over the special case.

**Comment by kirk86** [comment]
@takluyver Thank you Thomas. Would you say that is better to leave the kernels at
`~/.local/share/jupyter/kernels/python2`
`~/.local/share/jupyter/kernels/python3`
or it would be better to move them to the default indicated folder for kernels as described in the jupyter documentation, which is:

`/usr/local/share/jupyter/kernels/python2`
`/usr/local/share/jupyter/kernels/python3`

**Comment by takluyver** [comment]
The [docs describe both locations](http://jupyter-client.readthedocs.org/en/latest/kernels.html#kernel-specs). They're equally valid, just that one is specific to your user and one is not. On a desktop system, it doesn't make much difference, but FWIW I install my kernels in the user location `~/.local/...`.

**Comment by charli-polo** [comment]
Hi guys

http://ipython.readthedocs.org/en/latest/install/kernel_install.html is a clear doc but it's indeed difficult to find. Each time I need this page, I end up reading this thread. My trouble is that I make the search on the Jupyter keyword... Having this information on the Jupyter docs (currently it's on IPython) would be great because it adds some confusion for new users (like me...).

**Comment by takluyver** [comment]
I've opened jupyter/jupyter#116 to point to those instructions from the Jupyter docs about installing kernels.

**Comment by liuliangsir** [comment]
thx~

**Comment by dmaterialized** [comment]
THANK YOU!! You should know that this is still the only discussion of the issue that's made sense of the whole thing, in many hours of reading through iPython/Jupyter/Python docs and stackoverflow. `python3 -m ipykernel.kernelspec` is the only thing that has worked for me.
