### ISSUE TITLE
I am getting the connection failed error and struggling on it for quite a while now. Can someone please look into it, please?

### ISSUE THREAD

**Issue by ShahidNawaz01** [jupyter/jupyter#687]
![Connection Error](https://user-images.githubusercontent.com/106034173/246721298-0de791d6-e3b7-4497-9329-46515a44d97f.jpg)
I am getting the same error and struggling on it for quite a while now. Can someone please look into it, please?
I have also pasted the jupyter notebook output.

Error:
Connection failed
A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

Jupyter Notebook Output:
(base) C:\Users\shahi>jupyter notebook
[W 02:15:54.378 NotebookApp] Loading JupyterLab as a classic notebook (v6) extension.
[I 2023-06-19 02:15:54.393 LabApp] JupyterLab extension loaded from C:\ProgramData\anaconda3\lib\site-packages\jupyterlab
[I 2023-06-19 02:15:54.393 LabApp] JupyterLab application directory is C:\ProgramData\anaconda3\share\jupyter\lab
[I 02:15:56.356 NotebookApp] Serving notebooks from local directory: C:\Users\shahi
[I 02:15:56.356 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 02:15:56.356 NotebookApp] http://localhost:8888/?token=c8df5cac7d73fab8be02b18c4b3afc9b487acea79377bd44
[I 02:15:56.356 NotebookApp]  or http://127.0.0.1:8888/?token=c8df5cac7d73fab8be02b18c4b3afc9b487acea79377bd44
[I 02:15:56.356 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 02:15:56.388 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/shahi/AppData/Roaming/jupyter/runtime/nbserver-19840-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=c8df5cac7d73fab8be02b18c4b3afc9b487acea79377bd44
     or http://127.0.0.1:8888/?token=c8df5cac7d73fab8be02b18c4b3afc9b487acea79377bd44
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)
[I 02:16:02.669 NotebookApp] Kernel started: 33486188-89e9-4457-ad5e-68ba44f28bd0, name: python3
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\anaconda3\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\ProgramData\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 698, in start
    self.kernel.start()
  File "C:\ProgramData\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 212, in start
    super().start()
  File "C:\ProgramData\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 550, in start
    asyncio.run_coroutine_threadsafe(self.poll_control_queue(), control_loop.asyncio_loop)
  File "C:\ProgramData\anaconda3\lib\asyncio\tasks.py", line 892, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "C:\ProgramData\anaconda3\lib\asyncio\base_events.py", line 798, in call_soon_threadsafe
    self._check_closed()
  File "C:\ProgramData\anaconda3\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

(base) C:\Users\shahi>[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

_Originally posted by @ShahidNawaz01 in https://github.com/jupyter/notebook/issues/5024#issuecomment-1596228804_

**Comment by pra-sri** [comment]
It seems that you're encountering an issue with establishing a connection to the Jupyter Notebook server. Here are a few steps you can try to resolve the problem:
1.	**Ensure that the Jupyter Notebook server is running:** Based on the output you provided, the Jupyter Notebook server appears to be running correctly at http://localhost:8888/ with the provided token. Make sure that you have a web browser open and are accessing the correct URL.
2.	**Check the network connection:** Ensure that your network connection is stable and there are no firewall or proxy issues that could be preventing the notebook server from being accessed. You can try opening the Jupyter Notebook server URL in a different browser or on a different device to see if the issue persists.
3.	**Clear the Jupyter runtime directory:** It's possible that the Jupyter runtime directory has become corrupted, causing issues with the notebook server. Try deleting the contents of the directory mentioned in the error message: C:/Users/shahi/AppData/Roaming/jupyter/runtime/. After deleting the contents, restart the Jupyter Notebook server and see if the problem is resolved.
4.	**Update JupyterLab and Jupyter Notebook**: Ensure that you are using the latest versions of JupyterLab and Jupyter Notebook. You can update them by running the following command:

> pip install --upgrade jupyterlab notebook

5.	**Restart the Jupyter kernel:** If you're still encountering issues, try restarting the Jupyter kernel. You can do this by going to the "Kernel" menu in the JupyterLab interface and selecting "Restart Kernel". This will terminate the current kernel and start a new one, which might help resolve any internal issues.

If none of these steps solve the problem, please provide additional details about your system configuration, any recent changes or updates, and any error messages or logs that may be helpful in diagnosing the issue further.

**Comment by ivanov** [comment]
Per [this comment in the original thread](https://github.com/jupyter/notebook/issues/5024#issuecomment-1829245361) it seems @ShahidNawaz01 was able to resolve this issue. 

Happy hacking! :bowtie:
