### ISSUE TITLE
Question: how to install Python 2.7 as an additional kernel next to the default Python 3.X one? 

### ISSUE THREAD

**Issue by aragnon** [jupyter/jupyter#71]
I am using Jupyterhub, but the amount of inconsistent documentation is not helping. All I want is a fully featured (numpy, scikit*, etc.) Jupyter server up and running, which I expect it what most people want. 

The fact that there are three different projects: jupyterhub, jupyter, and ipython doesn't really help when every project sometimes refers to the documentation of the project they depend on.

**Comment by minrk** [comment]
Yup, the docs fragmentation is a serious problem. Since there are so many entrypoints, I think we are going to have to be okay with some amount of information duplication, since people are going to arrive from so many different directions.

Assuming you are using pip, you can install the `ipykernel` package with Python 2, and then install the kernelspec, so Jupyter knows how to start the kernel (no real difference if you use conda):

```bash
python2 -m pip install --upgrade ipykernel # install the kernel package for Python 2
python2 -m ipykernel install # register the Python 2 kernelspec
```

Installation of packages such as numpy, etc. is unaffected by Jupyter. The only additional step is installing the kernelspec after installing the kernel package itself, so that Jupyter can find the kernel. JupyterHub itself also has no effect on installation, other than the fact that you presumably want to do system-wide installs of packages and kernelspecs (generally the default already) so that all Hub users have access to what you install.

A totally complete installation of JupyterHub, notebook servers, and kernels for both Python 2 and 3 (sudo may be required, depending on the system):

```bash
python3 -m pip install jupyterhub notebook ipykernel
python3 -m ipykernel install # register Python 3 kernel (not technically necessary at this point, but a good idea)
python2 -m pip install ipykernel
python2 -m ipykernel install # register Python 2 kernel
```

And you can install whatever packages you want for Python 3 and/or Python 2 in the usual ways.

If you do the same with Anaconda, it's a bit easier to get all the way to a full scientific Python stack with multiple versions of Python:

```bash
# install everything (except JupyterHub itself) with Python 2 and 3. Jupyter is included in Anaconda.
conda create -n py3 python=3 anaconda
conda create -n py2 python=2 anaconda
# register py2 kernel
source activate py2
ipython kernel install
# same for py3, and install juptyerhub in the py3 env
source activate py3
ipython kernel install
pip install jupyterhub
```

I'll add something like this to the JuptyerHub docs.

**Comment by yaochx** [comment]
the same question, but I use pip3 install jupyter, so the following help me
`
python3 -m pip install jupyterhub notebook ipykernel
python3 -m ipykernel install # register Python 3 kernel (not technically necessary at this point, but a good idea)
python2 -m pip install ipykernel
python2 -m ipykernel install # register Python 2 kernel
`
 if using pip2, may be this will work for you, [referrence](http://stackoverflow.com/a/38516572)
`
python2 -m pip install ipykernel
python2 -m ipykernel install # register Python 2 kernel
python3 -m pip install jupyterhub notebook ipykernel
python3 -m ipykernel install # register Python 3 kernel (not technically necessary at this point, but a good idea)
`

**Comment by jacob-roth** [comment]
I'm trying to install on linux and after running:
```
pip install --upgrade setuptools --user python2
python2 -m pip install --upgrade ipykernel --user
python2 -m ipykernel install --user
```
am getting the following error: `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-0la809/tornado/`

Can you please advise? Thanks!

**Comment by MingGuan** [comment]
Maybe you need Anaconda to manage different version of Python?  Try this：
https://www.anaconda.com/

Hope this could help you.

Jake Roth <notifications@github.com> 于2018年9月11日周二 下午7:35写道：

**Comment by jacob-roth** [comment]
Thanks! I ended up finding that the issue was with `tornado` and SSL, and the following worked for me
```
pip install --upgrade "Tornado>=4.0.0,<5.0.0" --user
python2 -m pip install --upgrade ipykernel --user
python2 -m ipykernel install --user
```

**Comment by jianchao-li** [comment]
Hello, @minrk.

I followed your steps and I encountered the following problem: it is automatically pulling the latest `IPython` which is incompatible with `python2.7`.

**Comment by minrk** [comment]
In order to get the right version restrictions, you should make sure that you have recent pip (at least 10 or 18):

    pip install --upgrade pip

In general, it's a good idea to update pip any time you are going to use it.

**Comment by ben-alkov** [comment]
If you are using the `jupyter` command, this _will_ screw you.

The Python 2 and 3 `ipykernel` packages *both* install the full set of `jupyter*` scripts; you will end up running whichever was installed last.

**Comment by nabokov-ef** [comment]
conda create -n py27 python=2.7
Output:

> WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/msys2/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/msys2/win-64/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

How to solve this problem?
