### ISSUE TITLE
Incorrect CORS blocking

### ISSUE THREAD

**Issue by AgDude** [jupyter/jupyter#79]
The CORS implementation interferes with this chrome extension: 
[Allow-Control-Allow-Origin](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog)
This extension stops chrome from enforcing CORS rules, and is used by many developers.

I get this message in the log:
```
Blocking Cross Origin API request.  Origin: http://evil.com/, Host: 192.168.1.185:8888
```

Jupyter works fine in a browser profile without that extension, but with the extension (even disabled for the tab) it fails.

**Comment by takluyver** [comment]
I'm pretty sure there's a config option to allow requests from any origin - someone who knows that stuff better will be able to tell you what it is.

But we'd probably recommend that you do always run Jupyter in a profile without that extension, rather than disabling the security. If I understand what the extension is doing correctly, using it along with Jupyter is opening a major security hole - it potentially lets any website you visit run arbitrary code on your computer.

**Comment by minrk** [comment]
The server-side checks origin as well, because browsers do not do cross-origin checks for websockets. If you want the server to allow cross-origin access, you must specify that it should do so with:

```python
c.NotebookApp.allow_origin = '*'
```

in your jupyter_notebook_config.py.

**Comment by tankeryang** [comment]
@minrk   thx! I look around lot of issue then find the correct answer on you! It solved my problem!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/get-origin-of-the-request-in-notebook-config-py/7054/2
