### ISSUE TITLE
Line Numbers are not saved

### ISSUE THREAD

**Issue by jkwanth** [jupyter/jupyter#9]
Jupyter doesn't seem to save the line numbers. 

 I like the toggle line numbers feature in code cells or raw NBconvert cells, because they enhance the readability of these cells. However, when the notebook is saved, closed and re-opened, the line numbers disappear. Is this a bug?

Running this on:
    Mac OSX 10.10.4
    Python 2.7.10-0
    IPython 3.2.0

**Comment by Carreau** [comment]
It's not  technically a bug, as we don't try to persist it.

**Comment by takluyver** [comment]
This is a bit of a tricky decision. We could save it in cell metadata, but it's really part of the interface, not part of the document - if we're collaborating on a notebook in git, you might prefer line numbers on, and I might prefer them off. So it doesn't really make sense to store them in the notebook file.

Maybe the toggle should turn line numbers on or off for all code & raw cells, and store the value in frontend config so it persists for the user.

**Comment by minrk** [comment]
:+1: to all cells, store in frontend-config.

**Comment by willingc** [comment]
I'm closing this issue since line numbers are being addressed in the following places:

https://github.com/jupyter/notebook/issues/1244
https://github.com/jupyter/notebook/pull/1312

https://github.com/jupyter/notebook/issues/1244#issuecomment-203804754
[toggle_all_line_numbers extension mentioned in #1244](https://github.com/ipython-contrib/IPython-notebook-extensions/tree/master/nbextensions/usability/toggle_all_line_numbers)

Please feel free to comment on the open notebook issue or extension. :sunflower:
